# Generated by Django 2.2.24 on 2024-01-17 15:58

from django.db import migrations


def modify_type_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(modify_type_building_field),
    ]
