# Generated by Django 5.0.1 on 2024-01-18 16:16

from django.db import migrations


def migrate_owner_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flat_set = Flat.objects.all()
    if flat_set.exists():
        for flat in flat_set.iterator():
            owner, created = Owner.objects.get_or_create(
                owner=flat.owner,
                defaults={'owners_phonenumber': flat.owners_phonenumber,
                          'owner_pure_phone': flat.owner_pure_phone}
            )


def demigrate_owner_data(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owner_data, demigrate_owner_data),
    ]
